language: node_js
node_js: stable

before_install:
  - npm install -g npm
  - npm install -g yarn

install:
  - yarn install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "warriorsworld"
  - git config user.email "793588344@qq.com"
  - git add .
  - git commit -m "Update blog"
  - git push --force --quiet "https://${BL_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

cache:
  directories:
    - node_modules
# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - source-code 
env:
 global:
   - GH_REF: github.com/warriorsworld/warriorsworld.github.io.git

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - 793588344@qq.com
  on_success: change
  on_failure: always